### PR TITLE
Add ghc 8.0.1 to travis.yml

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Hi @phadej,

Like [`bifunctors`](https://github.com/ekmett/bifunctors/pull/40), this package needs a bit of TH-related love before it will compile warning-free with GHC 8.0.1, so let's hold off of this for now.

**Comment by phadej** [comment]
yeah, I just hoped it *could* work. :)

**Comment by elliottt** [comment]
I made a first pass at the TH-related changes needed in #32, and it builds with 8.0.1-rc1 for me.

**Comment by RyanGlScott** [comment]
Alright, it should be ready to work with GHC 8.0 now, so I'll merge this.

Expect a new Hackage release soon.

**Pull request merged**
